import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarOpen = true; //:TODO
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <ConvexClientProvider>
            <div className="flex h-screen bg-gray-50">
              <Sidebar />
              <div
                className={`flex-1 flex flex-col transition-all duration-300 ${sidebarOpen ? "ml-58" : "ml-20"}`}
              >
                <Header />
                <main className="flex-1 overflow-y-auto p-4 md:p-6">
                  {children}
                </main>
              </div>
            </div>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
